# Generated by Django 5.2.12 on 2026-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='token',
            field=models.TextField(default='dummy_token'),
            preserve_default=False,
        ),
    ]
